---
- name: Update NixOS on all hosts
  hosts: main
  strategy: free
  remote_user: sileanth
  tasks:
    - name: Pull latest changes from git
      ansible.builtin.git:
        repo: https://github.com/sileanth/nixosik-server.git
        dest: "/home/{{ ansible_user }}/nixosik-server"
        version: main
        update: yes

    - name: Rebuild NixOS system
      become: yes
      ansible.builtin.command:
        cmd: nixos-rebuild switch --flake .#
        chdir: "/home/{{ ansible_user }}/nixosik-server"
